import type { NichoEnum } from "@/lib/types";

export const ACTIVIDADES_POR_SECTOR: Record<NichoEnum, string[]> = {
  clinicas: [
    "Atención ambulatoria",
    "Hospitalización",
    "Diagnóstico por imágenes",
    "Laboratorio clínico",
    "Cirugía especializada",
  ],
  laboratorios: [
    "Análisis clínicos",
    "Pruebas genéticas",
    "Control de calidad de alimentos",
    "Investigación y desarrollo",
  ],
  escuelas: [
    "Educación inicial",
    "Educación básica",
    "Educación media/bachillerato",
    "Educación superior",
    "Capacitación y formación continua",
  ],
  escuelas_conduccion: ["Formación teórica", "Prácticas de manejo", "Certificación de conductores"],
  telecomunicaciones: [
    "Telefonía móvil",
    "Internet fijo",
    "Televisión por cable",
    "Servicios de datos empresariales",
  ],
  industriales: [
    "Manufactura",
    "Textiles",
    "Metalmecánica",
    "Plásticos",
    "Agroindustria",
  ],
  broker: ["Intermediación de seguros", "Asesoría de riesgos", "Gestión de siniestros"],
  grupos: [
    "Holding corporativo",
    "Gestión de subsidiarias",
    "Servicios compartidos",
    "Comercio e importación",
  ],
  restaurantes: [
  "Restaurante de servicio completo",
  "Comida rápida",
  "Cafetería",
  "Bar o lounge",
  "Delivery de alimentos",
  "Catering y eventos",
  "Panadería o pastelería",
  "Otra - especificar",
],
firma_legal: [
  "Asesoría legal corporativa",
  "Derecho laboral",
  "Derecho tributario",
  "Derecho civil",
  "Derecho penal",
  "Propiedad intelectual",
  "Protección de datos personales",
  "Cumplimiento normativo",
  "Litigios y arbitraje",
  "Notaría o servicios notariales",
  "Otra - especificar",
],
hoteles: [
  "Hospedaje turístico",
  "Hotel corporativo",
  "Hostal o alojamiento pequeño",
  "Resort",
  "Alquiler temporal",
  "Eventos y convenciones",
  "Restaurante y alimentos dentro del hotel",
  "Spa y bienestar",
  "Otra - especificar",
],
cooperativa: [
  "Captación de ahorros",
  "Otorgamiento de créditos",
  "Cobranza y recuperación de cartera",
  "Atención al socio",
  "Gestión de inversiones",
  "Servicios financieros complementarios",
  "Administración de seguros",
  "Otra - especificar",
],
otros: [
  "Comercio minorista",
  "Comercio mayorista",
  "Servicios profesionales",
  "Servicios administrativos",
  "Servicios tecnológicos",
  "Consultoría",
  "Transporte y logística",
  "Construcción",
  "Inmobiliaria",
  "Entretenimiento y eventos",
  "Organización sin fines de lucro",
  "Otra - especificar",
],
};
